🎨Design : OR-29
gaebal-saebal/early-order pull request #7
Opened 2023-07-21 16:12 UTC by js-ha

블랙 색상 : 2개

그레이 색상: 10개

숫자가 높아질수록 진한 색상입니다.

2023-07-21 16:55 UTC, js-ha commented
다른 의견인데, 색상을 저렇게 숫자로 말고 'F5F5F5'색상의 경우 GRAY_F5 이런식으로 하면 더 편하지 않을까요? 의견 부탁드려요!

2023-07-22 01:39 UTC, rosenfence requested changes
@js-ha 작성하셨던 comment처럼 GRAY_64 ~ GRAY_F5 이렇게 이름 바꾸는게 좀 더 좋아보이네요!!! 변경해서 다시 commit 부탁드릴게요 :D

2023-07-22 03:51 UTC, js-ha commented
수정하여 커밋하였습니다! 파일 확인하시고 머지 부탁드려요!

2023-07-22 11:39 UTC, Sonjiwon0 approved these changes
수정사항까지 확인했습니다!😊

2023-07-22 12:51 UTC, rosenfence reviewed
변경사항 확인했습니다!!

2023-07-22 12:52 UTC, merged